name: myapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  myapp:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:v1.0

    steps:
      - name: check repo
        uses: actions/checkout@v4

      - name: set up java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: build Spring Boot app
        run: ./mvnw clean package -DskipTests
        working-directory: user

      - name: docker hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build docker image
        run: docker build -t ${{ env.IMAGE_NAME }} ./user

      - name: push image
        run: docker push ${{ env.IMAGE_NAME }}

      - name: run container
        run: docker run -d -p 8080:8080 ${{ env.IMAGE_NAME }}

      - name: wait for app to start
        run: sleep 20

      - name: access the API
        run: curl http://localhost:8080/user
